create table account_verification (created_on timestamp not null, verification_code varchar(255) not null, user_id bigint not null, primary key (user_id));
create table admins (user_id bigint not null, primary key (user_id));
create table coaches (availability varchar(255), introduction varchar(255), xp integer, user_id bigint not null, primary key (user_id));
create table coaches_topics (coach_user_id bigint not null, topics_id bigint not null);
create table coaching_topic (id bigint not null, topic_topic_id integer, primary key (id));
create table coaching_topic_grades (coaching_topic_id bigint not null, grades integer);
create table members (id bigint not null, account_enabled boolean not null, email varchar(255) not null, first_name varchar(255), last_name varchar(255), password varchar(255), photo_url varchar(255), school_year varchar(255), primary key (id));
create table topics (topic_id integer not null, name varchar(255) not null, primary key (topic_id));
alter table coaches_topics add constraint UK_9l964dg81lk07ofqagvxbupow unique (topics_id);
alter table members add constraint UK_9d30a9u1qpg8eou0otgkwrp5d unique (email);
alter table topics add constraint UK_7tuhnscjpohbffmp7btit1uff unique (name);
alter tble account_verification add constraint FKglx0w7njieyv9xprt465m2i6q foreign key (user_id) references members;
alter table admins add constraint FKjoasa92wy96dlicsbfcdl5krg foreign key (user_id) references members;
alter table coaches add constraint FK5h0cksgba49yg6apbiie5wlvy foreign key (user_id) references members;
alter table coaches_topics add constraint FKhihfdn0xxsvr4bx9jaokql5pf foreign key (topics_id) references coaching_topic;
alter table coaches_topics add constraint FKfhcuxfpmbn4inpk0vidwea8s6 foreign key (coach_user_id) references coaches;
alter table coaching_topic add constraint FKl62wqdgeidhvwvp5j6qhpb8df foreign key (topic_topic_id) references topics;
alter table coaching_topic_grades add constraint FK13ryigkrx2nw7bkg78irl6uqq foreign key (coaching_topic_id) references coaching_topics;
set schema 'youcoach';
